"""Initial migration

Revision ID: 6fa480b0a35b
Revises: 
Create Date: 2026-01-16 12:34:21.441963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa480b0a35b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_hash_value', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_members_phone_hash_value'), ['phone_hash_value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_phone_hash_value'))
        batch_op.drop_column('phone_hash_value')

    # ### end Alembic commands ###
