"""Add coupon system fields

Revision ID: 9ea172f81dbd
Revises: 6fa480b0a35b
Create Date: 2026-01-19 11:59:28.262362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea172f81dbd'
down_revision = '6fa480b0a35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('redeemed_by_staff_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_substitutable', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_coupons_staff_id', 'staffs', ['redeemed_by_staff_id'], ['id'])

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_reward_balance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_lifetime_spend', sa.Integer(), nullable=True))

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('amount_claimed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('amount_claimed')
        batch_op.drop_column('status')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('total_lifetime_spend')
        batch_op.drop_column('current_reward_balance')

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_coupons_staff_id', type_='foreignkey')
        batch_op.drop_column('is_substitutable')
        batch_op.drop_column('redeemed_by_staff_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
